name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build the website
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.0
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: <username>/<repo-name>.github.io
          publish_dir: ./dist
